name: 'Test Application'

inputs:
    port:
        default: 80

    virtual_machine:
        required: true

runs:
    using: 'composite'
    steps:
        - name: (VINTNER) Test application
          shell: bash
          run: |
              cd ~/opera
              . .venv/bin/activate
              . /tmp/os-credentials.sh
              VIRTUAL_MACHINE_IP=$(openstack server show ${VIRTUAL_MACHINE_NAME} -f json | jq  -r '.addresses."public-belwue"[0]')

              echo "virtual machine name: ${VIRTUAL_MACHINE_NAME}"
              echo "virtual machine ip: ${VIRTUAL_MACHINE_IP}"

              curl --fail-with-body http://${VIRTUAL_MACHINE_IP}:${PORT}
          env:
              VIRTUAL_MACHINE_NAME: ${{ inputs.virtual_machine }}
              PORT: ${{ inputs.port }}
