---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: emailservice
    labels:
        app: emailservice
spec:
    selector:
        matchLabels:
            app: emailservice
    template:
        metadata:
            labels:
                app: emailservice
        spec:
            containers:
                - name: server
                  image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
                  ports:
                      - containerPort: 8080
                  env:
                      - name: PORT
                        value: '8080'
                      - name: DISABLE_PROFILER
                        value: '1'
                  readinessProbe:
                      periodSeconds: 5
                      grpc:
                          port: 8080
                  livenessProbe:
                      periodSeconds: 5
                      grpc:
                          port: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: emailservice
    labels:
        app: emailservice
spec:
    type: ClusterIP
    selector:
        app: emailservice
    ports:
        - name: grpc
          port: 5000
          targetPort: 8080
