---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: recommendationservice
    labels:
        app: recommendationservice
spec:
    selector:
        matchLabels:
            app: recommendationservice
    template:
        metadata:
            labels:
                app: recommendationservice
        spec:
            containers:
                - name: server
                  image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.1
                  ports:
                      - containerPort: 8080
                  readinessProbe:
                      periodSeconds: 5
                      grpc:
                          port: 8080
                  livenessProbe:
                      periodSeconds: 5
                      grpc:
                          port: 8080
                  env:
                      - name: PORT
                        value: '8080'
                      - name: PRODUCT_CATALOG_SERVICE_ADDR
                        value: 'productcatalogservice:3550'
                      - name: DISABLE_PROFILER
                        value: '1'

---
apiVersion: v1
kind: Service
metadata:
    name: recommendationservice
    labels:
        app: recommendationservice
spec:
    type: ClusterIP
    selector:
        app: recommendationservice
    ports:
        - name: grpc
          port: 8080
          targetPort: 8080
