---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: shippingservice
    labels:
        app: shippingservice
spec:
    selector:
        matchLabels:
            app: shippingservice
    template:
        metadata:
            labels:
                app: shippingservice
        spec:
            containers:
                - name: server
                  image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.1
                  ports:
                      - containerPort: 50051
                  env:
                      - name: PORT
                        value: '50051'
                      - name: DISABLE_PROFILER
                        value: '1'
                  readinessProbe:
                      periodSeconds: 5
                      grpc:
                          port: 50051
                  livenessProbe:
                      grpc:
                          port: 50051

---
apiVersion: v1
kind: Service
metadata:
    name: shippingservice
    labels:
        app: shippingservice
spec:
    type: ClusterIP
    selector:
        app: shippingservice
    ports:
        - name: grpc
          port: 50051
          targetPort: 50051
