version: '3'

silent: true

tasks:
    ###################################################
    #
    # Default
    #
    ###################################################

    # TODO: set base directory ...

    '*:*:*':
        cmd: bash tasks/{{index .MATCH 0}}/{{index .MATCH 1}}/{{index .MATCH 2}}/task.sh {{.CLI_ARGS}}

    # TODO: does not work. just have "*" and split it ...

    '*:*':
        cmd: bash tasks/{{index .MATCH 0}}/{{index .MATCH 1}}/task.sh {{.CLI_ARGS}}

    ###################################################
    #
    # Docs
    #
    ###################################################

    docs:build:commands:
        - bash node_modules/.bin/tsc -p tsconfig.tasks.json
        - bash node_modules/.bin/tsc-alias -p tsconfig.tasks.json
        - bash node_modules/.bin/syncdir tests build-tasks/tests --quiet
        - bash node_modules/.bin/syncdir src/assets build-tasks/src/assets --quiet
        - bash node_modules/.bin/syncdir tests build-tasks/tests --quiet
        - bash node_modules/.bin/syncdir tasks build-tasks/tasks --quiet
    docs:generate:interface: echo 'dont forget to run docs:build:commands in advance ...' && bash docs/cmds/command.sh interface
    docs:generate:dependencies: bash docs/cmds/command.sh dependencies
    docs:generate:tests:variability: bash docs/cmds/command.sh variability
    docs:generate:tests:query: bash docs/cmds/command.sh query
    docs:generate:sofdcar: bash docs/cmds/command.sh sofdcar
    docs:generate:puml: bash docs/cmds/puml/generate.sh
    docs:plot:puml: bash docs/cmds/puml/plot.sh
    docs:record:
        - task: docs:record:home
        - task: docs:record:getting-started
    docs:record:home: cd docs/cmds/casts && bash record.sh home
    docs:record:getting-started: cd docs/cmds/casts && bash record.sh getting-started

    docs:export: bash docs/cmds/export/generate.sh
    docs:export:local: bash docs/cmds/export/generate.sh http://localhost:8000
