---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: adservice
    labels:
        app: adservice
spec:
    selector:
        matchLabels:
            app: adservice
    template:
        metadata:
            labels:
                app: adservice
        spec:
            containers:
                - name: server
                  image: gcr.io/google-samples/microservices-demo/adservice:v0.10.1
                  ports:
                      - containerPort: 9555
                  env:
                      - name: PORT
                        value: '9555'
                  readinessProbe:
                      initialDelaySeconds: 20
                      periodSeconds: 15
                      grpc:
                          port: 9555
                  livenessProbe:
                      initialDelaySeconds: 20
                      periodSeconds: 15
                      grpc:
                          port: 9555

---
apiVersion: v1
kind: Service
metadata:
    name: adservice
    labels:
        app: adservice
spec:
    type: ClusterIP
    selector:
        app: adservice
    ports:
        - name: grpc
          port: 9555
          targetPort: 9555
