---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productcatalogservice
    labels:
        app: productcatalogservice
spec:
    selector:
        matchLabels:
            app: productcatalogservice
    template:
        metadata:
            labels:
                app: productcatalogservice
        spec:
            containers:
                - name: server
                  image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
                  ports:
                      - containerPort: 3550
                  env:
                      - name: PORT
                        value: '3550'
                      - name: DISABLE_PROFILER
                        value: '1'
                  readinessProbe:
                      grpc:
                          port: 3550
                  livenessProbe:
                      grpc:
                          port: 3550

---
apiVersion: v1
kind: Service
metadata:
    name: productcatalogservice
    labels:
        app: productcatalogservice
spec:
    type: ClusterIP
    selector:
        app: productcatalogservice
    ports:
        - name: grpc
          port: 3550
          targetPort: 3550
