@startuml
skinparam defaultFontName SansSerif
skinparam componentStyle rectangle

rectangle "worker" {
["application"] <<[[https://vintner.opentosca.org example.nodes.Application]]>> as application
file tar_archive <<[[https://vintner.opentosca.org tar.archive]]>> as application_artifact_0
application_artifact_0 - application

["runtime"] <<example.nodes.Runtime>> as runtime

}
rectangle "data" {
["database"] <<example.nodes.Database>> as database

["dbms"] <<example.nodes.DBMS>> as dbms

}

["compute"] <<example.nodes.Compute>> as compute


application --> runtime : host
application ..> database : database
runtime --> compute : host
database --> dbms : host
dbms --> compute : host

@enduml