dependencies:
    - source: ../unfurl-technology---shop---plus-original-automated-quality-maintenance/lib
    - source: ../unfurl-technology---shop---plus-original-automated-quality-maintenance/files
