default:
	/usr/bin/env bash .scripts/default.sh

puml:
	/usr/bin/env bash .scripts/puml.sh

plot:
	/usr/bin/env bash .scripts/plot.sh

validate:
	/usr/bin/env bash .scripts/validate.sh $(T)

validate-all:
	/usr/bin/env bash .scripts/validate-all.sh
