@startuml
skinparam componentStyle rectangle


rectangle "sofdcar.nodes.Python.Application"

rectangle "sofdcar.nodes.Python.Runtime"

rectangle "sofdcar.nodes.RaspberryPi.Hardware"

rectangle "sofdcar.nodes.Arduino.Software"

rectangle "sofdcar.nodes.Arduino.Software.C++"

rectangle "sofdcar.nodes.Arduino.Hardware"


"sofdcar.nodes.HPC.Software" <|-- "sofdcar.nodes.Python.Application"

"sofdcar.nodes.HPC.Software" <|-- "sofdcar.nodes.Python.Runtime"

"sofdcar.nodes.HPC.Hardware" <|-- "sofdcar.nodes.RaspberryPi.Hardware"

"sofdcar.nodes.ECU.Software" <|-- "sofdcar.nodes.Arduino.Software"

"sofdcar.nodes.Arduino.Software" <|-- "sofdcar.nodes.Arduino.Software.C++"

"sofdcar.nodes.ECU.Hardware" <|-- "sofdcar.nodes.Arduino.Hardware"

@enduml