@startuml
skinparam componentStyle rectangle


rectangle "artifact"

rectangle "source.archive"

rectangle "system.package"

rectangle "container.image"

rectangle "virtual.machine.image"


"tosca.artifacts.Root" <|-- "artifact"

"artifact" <|-- "source.archive"

"artifact" <|-- "system.package"

"artifact" <|-- "container.image"

"artifact" <|-- "virtual.machine.image"

@enduml