@startuml
skinparam componentStyle rectangle


rectangle "nodejs.runtime"

rectangle "nodejs.service.application"

rectangle "python.runtime"

rectangle "python.service.application"

rectangle "go.service.application"

rectangle "java.runtime"

rectangle "java.service.application"

rectangle "dotnet.runtime"

rectangle "csharp.service.application"

rectangle "binary.service.application"

rectangle "gcp.provider"

rectangle "gcp.service"

rectangle "gcp.cloudrun"

rectangle "gcp.cloudsql"

rectangle "gcp.appengine"

rectangle "gcp.appenginereporting"

rectangle "gcp.cloudbuild"

rectangle "docker.engine"

rectangle "kubernetes.cluster"

rectangle "openstack.provider"

rectangle "mysql.dbms"

rectangle "mysql.database"


"software.runtime" <|-- "nodejs.runtime"

"service.application" <|-- "nodejs.service.application"

"software.runtime" <|-- "python.runtime"

"service.application" <|-- "python.service.application"

"service.application" <|-- "go.service.application"

"software.runtime" <|-- "java.runtime"

"service.application" <|-- "java.service.application"

"software.runtime" <|-- "dotnet.runtime"

"service.application" <|-- "csharp.service.application"

"service.application" <|-- "binary.service.application"

"cloud.provider" <|-- "gcp.provider"

"cloud.service" <|-- "gcp.service"

"gcp.service" <|-- "gcp.cloudrun"

"gcp.service" <|-- "gcp.cloudsql"

"gcp.service" <|-- "gcp.appengine"

"gcp.service" <|-- "gcp.appenginereporting"

"gcp.service" <|-- "gcp.cloudbuild"

"container.runtime" <|-- "docker.engine"

"cloud.service" <|-- "kubernetes.cluster"

"cloud.provider" <|-- "openstack.provider"

"relational.dbms" <|-- "mysql.dbms"

"relational.database" <|-- "mysql.database"

@enduml