version: '3.8'

services:
    loadgenerator:
        #image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.1
        build: ../components/src/loadgenerator
        network_mode: host
        environment:
            - FRONTEND_ADDR=https://frontend-fgx2efhqra-ey.a.run.app/
            - USERS=10
