---
- hosts: localhost
  gather_facts: false
  tasks:
      - name: create security group
        openstack.cloud.security_group:
            name: unfurl-technology-ansible-motivation

      - name: open ports
        openstack.cloud.security_group_rule:
            security_group: unfurl-technology-ansible-motivation
            protocol: tcp
            port_range_min: '{{ item }}'
            port_range_max: '{{ item }}'
            remote_ip_prefix: '0.0.0.0/0'
            direction: ingress
            ethertype: IPv4
        loop: [69]
