apiVersion: apps/v1
kind: Deployment
metadata:
    name: shop
spec:
    selector:
        matchLabels:
            app: shop
    template:
        metadata:
            labels:
                app: shop
        spec:
            containers:
                - image: shop
                  imagePullPolicy: Never
                  name: shop
                  env:
                      - name: DB_NAME
                        value: shop

                      - name: DB_PASSWORD
                        value: password

                      - name: DB_USERNAME
                        value: root

                      - name: DB_ADDRESS
                        value: mysql

                      - name: DB_DIALECT
                        value: mysql

                  ports:
                      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: shop
spec:
    ports:
        - port: 80
    selector:
        app: shop
    type: NodePort
