# GitHub runner seems not to support ipv6, thus, we can not test on bwCloud.
# See https://github.com/actions/runner-images/issues/668

name: tmp
on:
    workflow_dispatch:
    schedule:
        - cron: '20 4 * * 2'
    push:
        branches:
            - fix-night-workflow

concurrency: tmp
jobs:
    night:
        name: tmp
        runs-on: ubuntu-22.04
        steps:
            - name: Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.13
                  #cache: pip

            - name: List
              run: ansible-galaxy collection list

            - name: Install
              run: ansible-galaxy collection install ansible.utils community.docker kubernetes.core

            - name: git
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"

            - name: Unfurl
              run: pip install unfurl==0.7.1

            - name: Init Unfurl Home
              run: unfurl home --init
