name: Zenodo
on:
    workflow_dispatch:
    push:
        branches:
            - fix-zenodo-workflow

concurrency: zenodo
jobs:
    zenodo:
        name: Zenodo
        runs-on: ubuntu-22.04
        steps:
            ###################################################
            #
            # Prepare
            #
            ###################################################

            - name: (PREPARE) Checkout Repository
              uses: actions/checkout@v3
              with:
                  lfs: true
                  fetch-depth: 0

            - name: (PREPARE) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.15.0
                  cache: yarn

            - name: (PREPARE) Install Node Dependencies
              run: rm -rf node_modules && yarn --immutable

            - name: (PREPARE) Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.13

            - name: (PREPARE) Install Python dependencies
              run: pip install -r cmds/zenodo/requirements.txt

            ###################################################
            #
            # Zenodo
            #
            ###################################################

            - name: (ZENODO) Download files
              run: |
                  mkdir -p cd /tmp/opentosca-vintner-zenodo-files
                  cd /tmp/opentosca-vintner-zenodo-files

                  gh release download latest

                  gh release download latest --archive=zip
                  mv opentosca-vintner-latest.zip opentosca-vintner.zip

                  gh release download latest --archive=tar.gz
                  mv opentosca-vintner-latest.tar.gz opentosca-vintner.tar.gz
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: (ZENODO) Create new Zenodo version
              run: yarn release:zenodo
              env:
                  ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
                  ZENODO_URL: ${{ secrets.ZENODO_URL }}
                  ZENODO_ORIGINAL_ID: ${{ secrets.ZENODO_ORIGINAL_ID }}
                  VINTNER_VERSION: ${{ github.sha }}
