name: Zenodo
on:
    workflow_dispatch:
    push:
        branches:
            - fix-zenodo-workflow

concurrency: zenodo
jobs:
    zenodo:
        name: Zenodo
        runs-on: ubuntu-22.04
        steps:
            ###################################################
            #
            # Prepare
            #
            ###################################################

            - name: (PREPARE) Checkout Repository
              uses: actions/checkout@v3
              with:
                  lfs: true
                  fetch-depth: 0

            - name: (PREPARE) Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.13
                  cache: pip

            ###################################################
            #
            # Zenodo
            #
            ###################################################

            - name: (ZENODO) Download files
              run: gh release download latest --dir /tmp/opentosca-vintner-zenodo-files

            - name: (ZENODO) Create new Zenodo version
              run: yarn release:zenodo
              env:
                  ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
                  ZENODO_URL: ${{ secrets.ZENODO_URL }}
                  ZENODO_ORIGINAL_ID: ${{ secrets.ZENODO_ORIGINAL_ID }}
                  VINTNER_VERSION: ${{ github.sha }}
